export type KnowledgeType = 'Career' | 'Course' | 'College' | 'Exam' | 'Scholarship'
export type KnowledgeRecord = { id:string; type:KnowledgeType; name:string; summary:string; field:string; location?:string; sourceName:string; sourceUrl:string; lastVerified:string; status:'verified'|'needs_review'; related:string[]; scope:'system'|'organisation' }

// Core records deliberately carry only source-backed facts. Changing facts belong in annual cycles/imports.
export const coreKnowledge: KnowledgeRecord[] = [
  {id:'career-software',type:'Career',name:'Software developer',summary:'Designs, builds and maintains software systems. Routes can include degrees, diplomas, apprenticeships and demonstrated skills.',field:'Technology',sourceName:'National Career Service',sourceUrl:'https://www.ncs.gov.in/',lastVerified:'2026-07-22',status:'needs_review',related:['course-btech-cse','exam-jee-main'],scope:'system'},
  {id:'career-nurse',type:'Career',name:'Registered nurse',summary:'Healthcare role requiring an approved education and registration pathway; requirements should be confirmed with the relevant regulator and institution.',field:'Healthcare',sourceName:'Indian Nursing Council',sourceUrl:'https://www.indiannursingcouncil.org/',lastVerified:'2026-07-22',status:'needs_review',related:['course-bsc-nursing','exam-neet'],scope:'system'},
  {id:'career-agri',type:'Career',name:'Agricultural scientist',summary:'Research and applied role spanning crops, soil, food systems and sustainable agriculture.',field:'Agriculture',sourceName:'Indian Council of Agricultural Research',sourceUrl:'https://icar.gov.in/',lastVerified:'2026-07-22',status:'needs_review',related:['course-bsc-agri','exam-cuet'],scope:'system'},
  {id:'course-btech-cse',type:'Course',name:'B.Tech. Computer Science and Engineering',summary:'Undergraduate engineering programme. Subject, eligibility and admissions rules vary by institution.',field:'Engineering',sourceName:'All India Council for Technical Education',sourceUrl:'https://www.aicte-india.org/',lastVerified:'2026-07-22',status:'needs_review',related:['career-software','exam-jee-main','college-iit-delhi'],scope:'system'},
  {id:'course-bsc-nursing',type:'Course',name:'B.Sc. Nursing',summary:'Undergraduate nursing programme; confirm current recognition, eligibility and registration requirements with the institution and regulator.',field:'Healthcare',sourceName:'Indian Nursing Council',sourceUrl:'https://www.indiannursingcouncil.org/',lastVerified:'2026-07-22',status:'needs_review',related:['career-nurse','exam-neet','college-aiims-delhi'],scope:'system'},
  {id:'course-bsc-agri',type:'Course',name:'B.Sc. Agriculture',summary:'Undergraduate programme covering agricultural science and related applied pathways.',field:'Agriculture',sourceName:'Indian Council of Agricultural Research',sourceUrl:'https://icar.gov.in/',lastVerified:'2026-07-22',status:'needs_review',related:['career-agri','exam-cuet'],scope:'system'},
  {id:'college-iit-delhi',type:'College',name:'Indian Institute of Technology Delhi',summary:'Institute of National Importance in New Delhi. Programme and admissions information must be checked on official pages.',field:'Engineering',location:'New Delhi',sourceName:'IIT Delhi',sourceUrl:'https://home.iitd.ac.in/',lastVerified:'2026-07-22',status:'verified',related:['course-btech-cse','exam-jee-main','exam-jee-advanced'],scope:'system'},
  {id:'college-aiims-delhi',type:'College',name:'All India Institute of Medical Sciences, New Delhi',summary:'Institution of National Importance in New Delhi. Check official admissions notices for programme-specific information.',field:'Healthcare',location:'New Delhi',sourceName:'AIIMS New Delhi',sourceUrl:'https://www.aiims.edu/',lastVerified:'2026-07-22',status:'verified',related:['course-bsc-nursing','exam-neet'],scope:'system'},
  {id:'college-tezpur',type:'College',name:'Tezpur University',summary:'Central University in Assam. Official programme and admissions information is maintained by the university.',field:'Multidisciplinary',location:'Assam',sourceName:'Tezpur University',sourceUrl:'https://www.tezu.ernet.in/',lastVerified:'2026-07-22',status:'verified',related:['exam-cuet','course-bsc-agri'],scope:'system'},
  {id:'exam-jee-main',type:'Exam',name:'JEE (Main)',summary:'National engineering entrance examination administered by the National Testing Agency. Dates and eligibility are cycle-specific.',field:'Engineering',sourceName:'National Testing Agency',sourceUrl:'https://jeemain.nta.nic.in/',lastVerified:'2026-07-22',status:'needs_review',related:['course-btech-cse','college-iit-delhi','exam-jee-advanced'],scope:'system'},
  {id:'exam-jee-advanced',type:'Exam',name:'JEE (Advanced)',summary:'Entrance examination for IIT admissions. The organising institute publishes annual eligibility and schedule information.',field:'Engineering',sourceName:'JEE (Advanced) 2026',sourceUrl:'https://jeeadv.ac.in/',lastVerified:'2026-07-22',status:'verified',related:['exam-jee-main','college-iit-delhi'],scope:'system'},
  {id:'exam-neet',type:'Exam',name:'NEET (UG)',summary:'National undergraduate medical entrance examination. Confirm the applicable cycle and counselling rules on official sources.',field:'Healthcare',sourceName:'National Testing Agency',sourceUrl:'https://neet.nta.nic.in/',lastVerified:'2026-07-22',status:'needs_review',related:['course-bsc-nursing','college-aiims-delhi'],scope:'system'},
  {id:'exam-cuet',type:'Exam',name:'CUET (UG)',summary:'Common University Entrance Test for undergraduate admissions; participating institutions and requirements vary.',field:'Multidisciplinary',sourceName:'National Testing Agency',sourceUrl:'https://cuet.nta.nic.in/',lastVerified:'2026-07-22',status:'verified',related:['college-tezpur','course-bsc-agri'],scope:'system'},
  {id:'scholarship-nsp',type:'Scholarship',name:'National Scholarship Portal',summary:'Government portal that hosts multiple scholarship schemes. Eligibility, deadlines and documents vary by scheme and cycle.',field:'Financial support',sourceName:'National Scholarship Portal',sourceUrl:'https://scholarships.gov.in/',lastVerified:'2026-07-22',status:'needs_review',related:['course-btech-cse','course-bsc-nursing'],scope:'system'},
  {id:'scholarship-insight',type:'Scholarship',name:'INSPIRE Scholarship for Higher Education',summary:'Science scholarship scheme. Confirm current guidelines, eligibility and application dates on the official portal.',field:'Science',sourceName:'Department of Science & Technology',sourceUrl:'https://online-inspire.gov.in/',lastVerified:'2026-07-22',status:'needs_review',related:['course-bsc-agri'],scope:'system'},
]
