import { useEffect, useState } from 'react'
import './Landing.css'

const features = [['Student records','A continuous, school-owned record for every student conversation.'],['Counselling sessions','Prepare, record decisions and carry the next action forward.'],['Career pathways','Compare primary and alternative routes in context.'],['Follow-ups','Turn guidance into clear responsibilities and timely check-ins.'],['Exams & deadlines','Keep official opportunities, dates and next steps visible.'],['School reports','See coverage, workload and interventions without exposing private notes.']]

export default function Landing({ openDashboard }: { openDashboard: () => void }) {
  const [intro, setIntro] = useState(false); const [revealed, setRevealed] = useState(false); const [active, setActive] = useState(0)
  useEffect(() => { const frame = requestAnimationFrame(() => setRevealed(true)); const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches; const seen = sessionStorage.getItem('cc-landing-seen'); if (!reduced && !seen) { setIntro(true); const id = window.setTimeout(() => { setIntro(false); sessionStorage.setItem('cc-landing-seen', '1') }, 3200); return () => { cancelAnimationFrame(frame); clearTimeout(id) } } }, [])
  return <div className={'landing ' + (revealed ? 'is-revealed' : '')}>
    <a className="skip-link" href="#main">Skip to content</a>
    {intro && <div className="intro-screen"><button onClick={() => { setIntro(false); sessionStorage.setItem('cc-landing-seen', '1') }}>Skip</button><div className="intro-compass"><i/><b/><em>•</em><em>•</em><em>•</em><em>•</em></div><strong>Career Compass</strong><p>Every student has a direction. We help schools make it visible.</p></div>}
    <header className="landing-head"><a className="landing-logo" href="/">✦ <span>career</span>compass</a><nav aria-label="Public navigation"><a href="#how">How it works</a><a href="#schools">For schools</a><a href="#features">Features</a><a href="#safety">Data safety</a></nav><button onClick={openDashboard}>Staff Login</button></header>
    <main id="main">
      <section className="hero"><div className="hero-copy"><p className="landing-eye">Career guidance infrastructure for schools</p><h1><span>Career</span> <i>Compass</i></h1><h2>Every student has a direction. We help schools make it visible.</h2><p>Career Compass helps counsellors and senior teachers manage student guidance, pathways, sessions, deadlines, follow-ups, and outcomes through one structured system.</p><div className="hero-actions"><button onClick={openDashboard}>Staff Login <span>→</span></button><a href="#features">Explore the platform</a></div></div><div className="hero-map" aria-label="A connected student guidance workflow"><div className="route route-a"/><div className="route route-b"/><article><small>STUDENT</small><b>Aarav Sharma</b><span>Pathway planning</span></article><article><small>NEXT ACTION</small><b>Review alternatives</b><span>Today · Maya Singh</span></article><article><small>VERIFIED</small><b>JEE (Advanced)</b><span>Official source · 22 Jul</span></article><div className="map-core">✦<small>GUIDANCE<br/>IN MOTION</small></div></div></section>
      <section className="problem" id="schools"><p className="landing-eye">The work behind the work</p><h2>Career guidance should not disappear into spreadsheets and scattered notes.</h2><p>Career Compass gives counsellors one calm place to connect student profiles, parent conversations, pathways, opportunities, actions and follow-ups—without asking teachers to become administrators.</p><div className="fragment-row">{['Sessions','Pathways','Deadlines','Follow-ups','Outcomes'].map(x=><span key={x}>{x}</span>)}</div></section>
      <section className="features" id="features"><div><p className="landing-eye">What it connects</p><h2>One continuous record of thoughtful guidance.</h2></div><div className="feature-grid">{features.map(([title, copy], i) => <button className={active === i ? 'feature active' : 'feature'} onClick={() => setActive(i)} key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{copy}</p><b>Explore <i>→</i></b></button>)}</div></section>
      <section className="how" id="how"><p className="landing-eye">A practical rhythm</p><h2>From first conversation to next step.</h2><ol>{['Import and organise student records.','Prepare for and conduct counselling sessions.','Build primary and alternative pathways.','Assign actions and follow-ups.','Track deadlines and interventions.','Review coverage and outcomes.'].map((step, i) => <li key={step}><span>{i + 1}</span>{step}</li>)}</ol></section>
      <section className="human"><div><p className="landing-eye">Built for counsellors, not instead of them</p><h2>Human guidance remains at the centre.</h2></div><p>Career Compass organises information, records decisions, and surfaces the next action. It does not decide a student’s future. The counsellor remains responsible for interpretation, discussion, and guidance.</p></section>
      <section className="safety" id="safety"><div><p className="landing-eye">Data safety</p><h2>Private by design. Useful by default.</h2><p>Staff-only access, organisation-scoped records, role-aware permissions, private counselling notes and counsellor-controlled sharing. No student or parent portal. No advertising. No sale of student data.</p></div><ul><li>Source-linked, visibly dated information</li><li>Shareable summaries exclude private notes</li><li>Audit-ready records and actions</li></ul></section>
      <section className="impact"><p className="landing-eye">Early field learning</p><h2>Piloted across approximately five government schools and used in guidance work reaching around 900 students and teachers.</h2><p>These early lessons shape a tool intended to let schools carry guidance work forward, year after year.</p></section>
      <section className="cta"><p className="landing-eye">Career Compass for schools</p><h2>Give every guidance conversation somewhere to lead.</h2><p>Bring student records, pathways, deadlines, interventions, and follow-ups into one continuous school guidance system.</p><button onClick={openDashboard}>Staff Login <span>→</span></button></section>
    </main><footer><div><b>✦ career compass</b><p>A counsellor-led guidance system for schools.</p></div><div><a href="#schools">For schools</a><a href="#how">How it works</a><a href="#features">Resources</a><a href="#safety">Data safety</a></div><button onClick={openDashboard}>Staff Login</button><small>© {new Date().getFullYear()} Career Compass</small></footer>
  </div>
}
