export type SubjectFeeling = 'love'|'like'|'neutral'|'dislike'|'not-studied'
export type Profile = { grade:string; stream:string; country:string; state:string; city:string; geography:string; relocate:string; mode:string; subjects:Record<string,SubjectFeeling>; bestSubjects:string[]; enjoyWeak:string[]; avoidSubjects:string[]; scoreBand:string; consistency:string; mathComfort:number; writingComfort:number; labComfort:number; examComfort:number; skills:Record<string,string>; activities:string[]; work:string[]; values:string[]; budget:string; scholarship:string; nearHome:boolean; examWillingness:string; duration:string; route:string[]; ideas:string[]; exclusions:string[] }
export type CareerMatch = { name:string; fit:number; band:string; why:string[]; concerns:string[]; pathways:string[]; kind:'strong'|'interdisciplinary'|'practical'|'explore' }

export const scoringWeights = { interest:25, skill:20, work:15, values:10, subjects:10, academic:10, feasibility:10 } as const
const catalogue = [
 {name:'Software & data systems',subjects:['mathematics','computer science','physics'],skills:['coding','analytical reasoning','data interpretation'],work:['working with data','working with ideas'],values:['intellectual challenge','job availability'],paths:['BTech / BCA / BSc Computer Science','Diploma or industry certification','JEE, state entrances or portfolio of projects']},
 {name:'Environmental policy & sustainability',subjects:['environmental science','geography','history','chemistry','biology'],skills:['research','writing','data interpretation'],work:['creating public impact','researching independently','working outdoors'],values:['social impact','international mobility'],paths:['BA / BSc Environmental Studies, Geography or Policy','Local conservation or vocational route','Build fieldwork and public-policy exposure']},
 {name:'Psychology, behaviour & UX research',subjects:['psychology','computer science','biology','literature'],skills:['empathy','listening','research','writing'],work:['working with people','researching independently','working with ideas'],values:['opportunity to help others','creativity'],paths:['BA/BSc Psychology or Cognitive Science','UX research / design pathway','Check postgraduate requirements before committing']},
 {name:'Design & visual communication',subjects:['fine arts','design','literature','computer science'],skills:['visual design','creativity','storytelling'],work:['designing things','performing'],values:['creativity','independence'],paths:['BDes / BFA / communication design','Portfolio, diploma or certification route','NID/NIFT/UCEED where relevant; portfolio is central']},
 {name:'Commerce, finance & entrepreneurship',subjects:['economics','accountancy','business studies','mathematics'],skills:['numerical problem-solving','entrepreneurship','planning','negotiation'],work:['building businesses','managing projects','working with data'],values:['income potential','entrepreneurship','leadership'],paths:['BCom / BBA / Economics','CA, CMA or finance certifications','Local/public college plus work experience route']},
 {name:'Health, community & allied care',subjects:['biology','chemistry','psychology','physical education'],skills:['empathy','caregiving','experimentation','listening'],work:['helping people directly','working in laboratories'],values:['social impact','job stability'],paths:['Allied health, nursing, public health or psychology','Diploma and community-health routes','Medicine requires PCB and NEET readiness']},
 {name:'Law, policy & public affairs',subjects:['legal studies','political science','history','literature'],skills:['writing','public speaking','research','persuasion'],work:['persuading or negotiating','creating public impact'],values:['government service','social impact','prestige'],paths:['BA LLB / LLB / public policy','CLAT and other entrances where applicable','Debate, reading and writing exposure route']},
 {name:'Applied engineering & technical operations',subjects:['mathematics','physics','engineering drawing','vocational subjects'],skills:['building physical things','fixing systems','spatial reasoning','attention to detail'],work:['working with machines','active work'],values:['job availability','job stability'],paths:['BTech / BE','Polytechnic diploma → lateral entry or employment','ITI / apprenticeship / local technical training']},
 {name:'Media, writing & communication',subjects:['literature','languages','history','psychology'],skills:['writing','storytelling','public speaking','language learning'],work:['public-facing work','working with ideas'],values:['creativity','geographic flexibility'],paths:['Journalism, communications or liberal arts degree','Portfolio / freelance / certification route','Build published work and interview practitioners']},
]
const normal=(x:string)=>x.trim().toLowerCase()
const overlap=(wanted:string[], selected:string[])=>wanted.filter(x=>selected.includes(normal(x))).length
export function buildMatches(profile:Profile):CareerMatch[] {
 const enjoyed=Object.entries(profile.subjects).filter(([,v])=>v==='love'||v==='like').map(([x])=>normal(x)); const disliked=Object.entries(profile.subjects).filter(([,v])=>v==='dislike').map(([x])=>normal(x)); const skills=Object.entries(profile.skills).filter(([,v])=>v==='enjoy'||v==='good').map(([x])=>normal(x))
 return catalogue.map(c=>{const subject=(overlap(c.subjects,enjoyed)/c.subjects.length)*35; const skill=(overlap(c.skills,skills)/c.skills.length)*20; const work=(overlap(c.work,profile.work.map(normal))/c.work.length)*15; const value=(overlap(c.values,profile.values.map(normal))/c.values.length)*10; const penalty=(overlap(c.subjects,disliked)/c.subjects.length)*15; const academic=profile.scoreBand&&profile.scoreBand!=='Prefer not to answer'?7:3; const feasibility=profile.budget==='Under ₹50,000'||profile.nearHome?5:8; const fit=Math.max(12,Math.min(94,Math.round(subject+skill+work+value+academic+feasibility-penalty))); const why=[...c.subjects.filter(x=>enjoyed.includes(x)).slice(0,2),...c.skills.filter(x=>skills.includes(x)).slice(0,2)].map(x=>`matches ${x}`); const concerns:string[]=[]; if(penalty) concerns.push('Includes a subject you marked as a possible avoidance.'); if(profile.examWillingness==='Avoid if possible') concerns.push('Some routes may use competitive entrance examinations.'); if(!why.length) concerns.push('There is limited direct evidence in your profile—explore this before deciding.'); const kind:CareerMatch['kind']=fit>=70?'strong':c.subjects.some(x=>enjoyed.includes(x))&&enjoyed.length>2?'interdisciplinary':c.name.includes('Applied')?'practical':'explore'; return {name:c.name,fit,band:fit>=70?'Strong fit':fit>=55?'Worth exploring':fit>=42?'Possible fit':'Low-confidence match',why:why.length?why:['mixed interests and work preferences'],concerns,pathways:c.paths,kind} }).sort((a,b)=>b.fit-a.fit)
}
export const profileConfidence=(p:Profile)=>Math.round(([p.grade,p.stream,p.scoreBand,p.budget].filter(Boolean).length/4*35)+(Math.min(1,Object.keys(p.subjects).length/5)*30)+(Math.min(1,Object.keys(p.skills).length/4)*20)+(Math.min(1,p.work.length/3)*15))
