-- Personalised diagnostic and explainable recommendation records.
-- RLS is deliberately deferred: this database does not yet have an authenticated organisation model.
alter table student_profiles add column if not exists country text, add column if not exists city text, add column if not exists study_mode text, add column if not exists profile_confidence smallint, add column if not exists missing_information text[] default '{}';
create table if not exists student_skills (id uuid primary key default gen_random_uuid(), profile_id uuid not null references student_profiles(id) on delete cascade, skill_name text not null, relationship text not null check (relationship in ('enjoy','good','improve','do_not_enjoy')), rank smallint, unique(profile_id,skill_name));
create table if not exists student_work_preferences (id uuid primary key default gen_random_uuid(), profile_id uuid not null references student_profiles(id) on delete cascade, preference_name text not null, strength smallint check(strength between 1 and 5), unique(profile_id,preference_name));
create table if not exists student_values (id uuid primary key default gen_random_uuid(), profile_id uuid not null references student_profiles(id) on delete cascade, value_name text not null, rank smallint, unique(profile_id,value_name));
create table if not exists student_constraints (id uuid primary key default gen_random_uuid(), profile_id uuid not null references student_profiles(id) on delete cascade, constraint_type text not null, value text, hard_constraint boolean default false, unique(profile_id,constraint_type));
create table if not exists student_existing_options (id uuid primary key default gen_random_uuid(), profile_id uuid not null references student_profiles(id) on delete cascade, option_type text not null, option_name text not null, sentiment text, unique(profile_id,option_type,option_name));
create table if not exists diagnostic_sessions (id uuid primary key default gen_random_uuid(), profile_id uuid not null references student_profiles(id) on delete cascade, engine_version text not null, status text not null default 'in_progress', started_at timestamptz not null default now(), completed_at timestamptz);
create table if not exists diagnostic_answers (id uuid primary key default gen_random_uuid(), session_id uuid not null references diagnostic_sessions(id) on delete cascade, section text not null, question_key text not null, answer jsonb not null, confidence smallint, unique(session_id,question_key));
create table if not exists recommendation_weight_configs (id uuid primary key default gen_random_uuid(), organisation_id text not null, name text not null default 'Default transparent engine', weights jsonb not null, active boolean not null default true, created_at timestamptz not null default now());
create table if not exists recommendation_runs (id uuid primary key default gen_random_uuid(), profile_id uuid not null references student_profiles(id) on delete cascade, session_id uuid references diagnostic_sessions(id) on delete set null, weight_config_id uuid references recommendation_weight_configs(id), engine_version text not null, profile_snapshot jsonb not null, created_at timestamptz not null default now());
create table if not exists recommendation_scores (id uuid primary key default gen_random_uuid(), run_id uuid not null references recommendation_runs(id) on delete cascade, entity_type text not null, entity_id text, entity_name text not null, score numeric(5,2), fit_band text, confidence smallint, hard_excluded boolean default false, missing_data text[] default '{}', unique(run_id,entity_type,entity_name));
create table if not exists recommendation_explanations (id uuid primary key default gen_random_uuid(), score_id uuid not null references recommendation_scores(id) on delete cascade, matched_fields jsonb not null default '[]', penalties jsonb not null default '[]', scoring_factors jsonb not null default '{}', narrative text not null, created_at timestamptz not null default now());
create table if not exists student_career_matches (id uuid primary key default gen_random_uuid(), profile_id uuid not null references student_profiles(id) on delete cascade, career_id text references careers(career_id), score_id uuid references recommendation_scores(id) on delete set null, status text, pinned boolean default false, unique(profile_id,career_id));
create table if not exists student_course_matches (id uuid primary key default gen_random_uuid(), profile_id uuid not null references student_profiles(id) on delete cascade, course_id text references courses(course_id), score_id uuid references recommendation_scores(id) on delete set null, unique(profile_id,course_id));
create table if not exists student_college_matches (id uuid primary key default gen_random_uuid(), profile_id uuid not null references student_profiles(id) on delete cascade, institution_programme_id uuid references institution_programmes(id), score_id uuid references recommendation_scores(id) on delete set null, category text check(category in ('aspirational','target','realistic','safer','currently_ineligible','insufficient_data')), unique(profile_id,institution_programme_id));
create table if not exists student_exam_matches (id uuid primary key default gen_random_uuid(), profile_id uuid not null references student_profiles(id) on delete cascade, exam_id text references exams(exam_id), score_id uuid references recommendation_scores(id) on delete set null, unique(profile_id,exam_id));
create table if not exists student_scholarship_matches (id uuid primary key default gen_random_uuid(), profile_id uuid not null references student_profiles(id) on delete cascade, scholarship_id text references scholarships(scholarship_id), score_id uuid references recommendation_scores(id) on delete set null, unique(profile_id,scholarship_id));
create table if not exists counsellor_overrides (id uuid primary key default gen_random_uuid(), profile_id uuid not null references student_profiles(id) on delete cascade, score_id uuid references recommendation_scores(id) on delete set null, counsellor_external_id text not null, action text not null, reason text not null, previous_value jsonb, new_value jsonb, created_at timestamptz not null default now());
create index if not exists diagnostic_sessions_profile_idx on diagnostic_sessions(profile_id,started_at desc);
create index if not exists recommendation_runs_profile_idx on recommendation_runs(profile_id,created_at desc);
create index if not exists recommendation_scores_run_idx on recommendation_scores(run_id,entity_type);
