-- Indian-context student profile and admissions architecture. Apply after organisation/student identity tables are connected.
create table if not exists student_profiles (id uuid primary key default gen_random_uuid(), organisation_id text not null, student_external_id text not null, current_stage text not null, board text, board_state text, stream text, academic_year text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organisation_id,student_external_id));
create table if not exists student_subject_preferences (id uuid primary key default gen_random_uuid(), profile_id uuid not null references student_profiles(id) on delete cascade, subject_id text references subjects(subject_id), subject_name text not null, currently_studying boolean, enjoyment smallint check(enjoyment between 1 and 5), confidence smallint check(confidence between 1 and 5), willingness_to_improve smallint check(willingness_to_improve between 1 and 5), marks_band text, source text, updated_at timestamptz not null default now(), unique(profile_id,subject_name));
create table if not exists student_academic_records (id uuid primary key default gen_random_uuid(), profile_id uuid not null references student_profiles(id) on delete cascade, overall_band text, subject_name text, percentage numeric(5,2), grade text, board_exam boolean default false, academic_year text, verification_status text default 'student_reported', source text, recorded_at timestamptz not null default now());
create table if not exists student_financial_profiles (profile_id uuid primary key references student_profiles(id) on delete cascade, annual_tuition_budget_band text, annual_total_budget_band text, scholarship_required boolean, government_preferred boolean, private_with_scholarship_only boolean, loan_open boolean, hostel_affordable boolean, relocation_affordable boolean, application_fee_constraint boolean, coaching_access text, local_study_preference boolean, visibility text default 'counsellor_restricted', updated_at timestamptz not null default now());
create table if not exists student_geography_profiles (profile_id uuid primary key references student_profiles(id) on delete cascade, home_state text, home_district text, home_city text, preferred_states text[], excluded_states text[], relocation_scope text, hostel_willing boolean, metro_willing boolean, commute_preference text, language_preferences text[], transport_constraints text, updated_at timestamptz not null default now());
create table if not exists student_route_preferences (id uuid primary key default gen_random_uuid(), profile_id uuid not null references student_profiles(id) on delete cascade, route_type text not null, openness smallint check(openness between 1 and 5), exam_preparation_readiness smallint check(exam_preparation_readiness between 1 and 5), weekly_preparation_hours smallint, gap_year_open boolean, unique(profile_id,route_type));
create table if not exists institution_programmes (id uuid primary key default gen_random_uuid(), institution_id text not null references institutions(institution_id), course_id text references courses(course_id), programme_name text not null, degree_level text, duration text, mode text, active boolean default true, verification_status text not null default 'needs_review', data_sufficient boolean default false, last_verified_at timestamptz, unique(institution_id,programme_name));
create table if not exists institution_programme_sources (id uuid primary key default gen_random_uuid(), institution_programme_id uuid not null references institution_programmes(id) on delete cascade, source_name text not null, source_url text not null, source_year text, last_verified_at timestamptz, status text default 'needs_review');
create table if not exists institution_programme_eligibility (id uuid primary key default gen_random_uuid(), institution_programme_id uuid not null references institution_programmes(id) on delete cascade, required_subjects text[], minimum_percentage numeric(5,2), board_rule text, exam_id text references exams(exam_id), age_rule text, source_id uuid references institution_programme_sources(id), verification_status text default 'needs_review');
create table if not exists institution_programme_fees (id uuid primary key default gen_random_uuid(), institution_programme_id uuid not null references institution_programmes(id) on delete cascade, cycle_year text, tuition_amount numeric, hostel_amount numeric, currency text default 'INR', source_id uuid references institution_programme_sources(id), verification_status text default 'needs_review');
create table if not exists admission_cycles (id uuid primary key default gen_random_uuid(), institution_programme_id uuid not null references institution_programmes(id) on delete cascade, cycle_year text not null, application_open date, application_close date, counselling_authority text, domicile_rule text, source_id uuid references institution_programme_sources(id), stale_after date, verification_status text default 'needs_review');
create table if not exists admission_cutoffs (id uuid primary key default gen_random_uuid(), admission_cycle_id uuid not null references admission_cycles(id) on delete cascade, quota_or_category text, opening_rank numeric, closing_rank numeric, minimum_score numeric, source_id uuid references institution_programme_sources(id), verification_status text default 'needs_review');
create index if not exists student_profiles_org_idx on student_profiles(organisation_id,student_external_id); create index if not exists institution_programmes_course_idx on institution_programmes(course_id,verification_status); create index if not exists admissions_cycle_stale_idx on admission_cycles(stale_after,verification_status);
