-- Verified pathway/admissions model. Programme-level rows remain empty until official sources are imported.
create table if not exists career_pathways (id uuid primary key default gen_random_uuid(), career_id text not null references careers(career_id), name text not null, route_type text not null, verification_status text not null default 'needs_review', source_url text, unique(career_id,name));
create table if not exists career_pathway_steps (id uuid primary key default gen_random_uuid(), pathway_id uuid not null references career_pathways(id) on delete cascade, sequence smallint not null, phase text not null, title text not null, detail text, mandatory boolean default false, source_url text, unique(pathway_id,sequence));
create table if not exists college_program_admission_routes (id uuid primary key default gen_random_uuid(), institution_programme_id uuid not null references institution_programmes(id) on delete cascade, route_type text not null, application_method text, official_url text, verification_status text not null default 'needs_review');
create table if not exists college_program_exam_requirements (id uuid primary key default gen_random_uuid(), admission_route_id uuid not null references college_program_admission_routes(id) on delete cascade, exam_id text references exams(exam_id), required boolean default true, source_url text, verification_status text not null default 'needs_review');
create table if not exists college_program_application_cycles (id uuid primary key default gen_random_uuid(), admission_route_id uuid not null references college_program_admission_routes(id) on delete cascade, cycle_year text not null, registration_open date, registration_close date, counselling_open date, allotment_date date, official_url text, verification_status text not null default 'needs_review');
create table if not exists college_program_documents (id uuid primary key default gen_random_uuid(), admission_route_id uuid not null references college_program_admission_routes(id) on delete cascade, document_name text not null, required boolean default true, source_url text, verification_status text not null default 'needs_review');
create table if not exists college_program_costs (id uuid primary key default gen_random_uuid(), institution_programme_id uuid not null references institution_programmes(id) on delete cascade, cycle_year text, cost_type text not null, amount numeric, currency text default 'INR', source_url text, verification_status text not null default 'needs_review');
create table if not exists college_program_scholarships (id uuid primary key default gen_random_uuid(), institution_programme_id uuid not null references institution_programmes(id) on delete cascade, scholarship_id text references scholarships(scholarship_id), source_url text, verification_status text not null default 'needs_review');
create table if not exists student_roadmaps (id uuid primary key default gen_random_uuid(), organisation_id text not null, student_external_id text not null, recommendation_run_id uuid references recommendation_runs(id), target_career_id text references careers(career_id), target_course_id text references courses(course_id), target_institution_programme_id uuid references institution_programmes(id), admission_cycle_id uuid references college_program_application_cycles(id), engine_version text not null, status text not null default 'draft', confidence smallint, missing_data_warnings text[] default '{}', generated_at timestamptz not null default now());
create table if not exists student_roadmap_options (id uuid primary key default gen_random_uuid(), roadmap_id uuid not null references student_roadmaps(id) on delete cascade, option_type text not null, label text not null, selected boolean default false, reason text);
create table if not exists student_roadmap_steps (id uuid primary key default gen_random_uuid(), roadmap_id uuid not null references student_roadmaps(id) on delete cascade, phase text not null, sequence smallint not null, title text not null, detail text, mandatory boolean default false, completed_at timestamptz, due_date date, source_url text, unique(roadmap_id,sequence));
create table if not exists student_roadmap_notes (id uuid primary key default gen_random_uuid(), roadmap_id uuid not null references student_roadmaps(id) on delete cascade, counsellor_external_id text not null, note text not null, created_at timestamptz not null default now());
create table if not exists roadmap_alternatives (id uuid primary key default gen_random_uuid(), roadmap_id uuid not null references student_roadmaps(id) on delete cascade, alternative_roadmap_id uuid references student_roadmaps(id), alternative_type text not null, reason text);
create table if not exists admissions_checklists (id uuid primary key default gen_random_uuid(), roadmap_id uuid not null references student_roadmaps(id) on delete cascade, item_type text not null, label text not null, required boolean default true, completed_at timestamptz, source_url text);
create index if not exists student_roadmaps_student_idx on student_roadmaps(organisation_id,student_external_id,generated_at desc);
