-- Source-attributed Career Compass discovery data. Date-sensitive fields remain text/blank until editorial verification.
create table if not exists sources (source_id text primary key, source_name text not null, publisher text, url text, content_type text, vintage text, trust_level text, notes text);
create table if not exists career_taxonomy (node_id text primary key, level text, code text, title text, parent_code text, source_name text, source_url text, verification_status text);
create table if not exists careers (career_id text primary key, nco_code text unique, title text not null, alternate_titles text, division_code text, division_title text, subdivision_code text, subdivision_title text, group_code text, group_title text, family_code text, family_title text, nco_2004_code text, description text, education_routes text, skills text, school_subjects text, source_name text, source_url text, source_vintage text, verification_status text not null default 'needs_review', content_status text, last_reviewed text);
create table if not exists universities (university_id text primary key, university_name text not null, state_inferred_from_affiliated_colleges text, country text, official_website text, university_type text, source_name text, source_url text, verification_status text not null default 'needs_review', last_reviewed text);
create table if not exists institutions (institution_id text primary key, institution_name text not null, institution_type text, affiliating_university_id text references universities(university_id), affiliating_university_name text, state text, district text, country text, official_website text, recognition_status text, source_name text, source_url text, source_vintage text, verification_status text not null default 'needs_current_reverification', publish_recommendation text, last_reviewed text);
create table if not exists courses (course_id text primary key, course_name text not null, award_level text, degree_family text, field text, category text, route_type text, typical_duration text, typical_entry_stage text, typical_subject_requirements text, description text, career_keywords text, source_basis text, source_url text, verification_status text not null default 'needs_review', publish_recommendation text);
create table if not exists exams (exam_id text primary key, acronym text, exam_name text not null, conducting_body text, category text, scope text, typical_purpose text, official_url text, application_start text, application_deadline text, exam_date text, date_policy text, verification_status text not null default 'needs_review', last_reviewed text, is_active text);
create table if not exists scholarships (scholarship_id text primary key, scholarship_name text not null, provider text, category text, geographic_scope text, eligibility_summary text, benefit_summary text, application_window text, official_url text, verification_status text not null default 'needs_review', date_policy text, last_reviewed text);
create table if not exists subjects (subject_id text primary key, subject_name text not null, subject_group text, verification_status text);
create table if not exists course_subject_links (course_id text references courses(course_id), subject_id text references subjects(subject_id), relationship_type text, confidence text, verification_status text, primary key(course_id,subject_id,relationship_type));
create table if not exists career_subject_links (career_id text references careers(career_id), subject_id text references subjects(subject_id), relationship_type text, confidence text, verification_status text, primary key(career_id,subject_id,relationship_type));
create table if not exists career_course_links (course_id text references courses(course_id), career_id text references careers(career_id), relationship_type text, confidence text, verification_status text, primary key(course_id,career_id,relationship_type));
create table if not exists exam_course_links (exam_id text references exams(exam_id), course_id text references courses(course_id), relationship_type text, verification_status text, primary key(exam_id,course_id,relationship_type));
create index if not exists careers_title_idx on careers using gin (to_tsvector('english', coalesce(title,'') || ' ' || coalesce(alternate_titles,'') || ' ' || coalesce(description,'')));
create index if not exists institutions_name_idx on institutions(institution_name);
create index if not exists institutions_state_idx on institutions(state, verification_status);
create index if not exists courses_name_idx on courses(course_name);
